version: '3.8'

services:
  db:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    # restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - 3306:3306

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8003:8000
    env_file:
      - .env
    environment:
      - MODE=server
      - SQL_HOST=host.docker.internal
      - PORT=8000
      - BASE_URL=http://localhost:8002
    # restart: unless-stopped

volumes:
  mysql_data:
